export default function ProblemAnalyticsCard({
  analytics,
}) {
  if (!analytics) return null;

  return (
    <div className="rounded-2xl border border-white/10 bg-surface p-8 shadow-lg">

      <div className="flex items-center justify-between">

        <div>
          <h2 className="text-3xl font-bold">
            AI Memory Report
          </h2>

          <p className="mt-2 text-text-muted">
            Generated by CodeRevise AI V8
          </p>
        </div>

        <div className="rounded-xl bg-cyan-500/10 px-5 py-3">

          <div className="text-xs uppercase tracking-wider text-cyan-400">
            Health
          </div>

          <div className="text-3xl font-bold text-cyan-400">
            {analytics.memoryHealth}%
          </div>

        </div>

      </div>

      <div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">

        <Stat
          title="Memory Stage"
          value={analytics.memoryStage}
        />

        <Stat
          title="Forget Risk"
          value={analytics.forgetRisk}
        />

        <Stat
          title="Next Review"
          value={`${analytics.nextRevisionIn} Days`}
        />

        <Stat
          title="Retention"
          value={`${analytics.currentRetention}%`}
        />

      </div>

      <div className="mt-10">

        <Progress
          title="Memory Strength"
          value={analytics.strength}
          max={40}
        />

        <Progress
          title="Stability"
          value={analytics.stability}
          max={1500}
        />

        <Progress
          title="Retrievability"
          value={analytics.retrievability}
          max={100}
        />

      </div>

    </div>
  );
}

function Stat({
  title,
  value,
}) {
  return (
    <div className="rounded-xl border border-white/10 bg-background/40 p-5">

      <p className="text-sm text-text-muted">
        {title}
      </p>

      <h3 className="mt-2 text-2xl font-bold">
        {value}
      </h3>

    </div>
  );
}

function Progress({
  title,
  value,
  max,
}) {
  const percent = Math.min(
    100,
    (value / max) * 100,
  );

  return (
    <div className="mb-7">

      <div className="mb-2 flex justify-between">

        <span>{title}</span>

        <span className="font-semibold">
          {value}
        </span>

      </div>

      <div className="h-3 rounded-full bg-white/10">

        <div
          className="h-3 rounded-full bg-cyan-500 transition-all duration-700"
          style={{
            width: `${percent}%`,
          }}
        />

      </div>

    </div>
  );
}